[build]
  command = "npm run build"
  publish = "build"  # Agar React bo'lsa. Vue (Vite) bo'lsa "dist"
  functions = "netlify/functions"  # Agar serverless functions ishlatilsa

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
